apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: sayurbox
  name: sayurbox
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sayurbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sayurbox
    spec:
      containers:
      - image: falgifaisal/node-hello
        imagePullPolicy: Always
        name: sayurbox
        ports:
        - containerPort: 7000
        env:
          - name: PORT
            value: "7000"
        resources: 
          requests:
            cpu: {{ .Values.requestCpu }}
            memory: {{ .Values.requestMemory }}
          limits:
            cpu: {{ .Values.limitsCpu }}
            memory: {{ .Values.limitsMemory }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 300
          failureThreshold: 300
          periodSeconds: 300
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
