apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: sayurbox
spec:
  maxReplicas: {{ .Values.replicasMax }}
  minReplicas: {{ .Values.replicasMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sayurbox
  targetCPUUtilizationPercentage: {{ .Values.cpuUtilization }}
