apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sayurbox
    app.kubernetes.io/managed-by: Helm
  name: sayurbox
spec:
  type: {{ .Values.servicesType }}
  ports:
  - port: {{ .Values.servicesPort }}
    protocol: TCP
    targetPort: {{ .Values.servicesPort }}
  selector:
    app: sayurbox
status:
  loadBalancer: {}
